name: CI-Stage

on:
  push:
    branches: [ main ]
  pull_request:
    #branches: [ $default-branch ]
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blogsapp:${{github.sha}}
  
  UpdatingImageTag:
    runs-on: ubuntu-latest
    steps:
      - name: Updating Image tag to deploy
        run: |
            echo "Listing..........."
            ls
            pwd
