name: CI-Stage

on:
  push:
    branches: [ main ]
  pull_request:
    #branches: [ $default-branch ]
    branches: [ main ]

jobs:
  dockerBuildAndPush:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blogsapp:${{github.sha}}
  
  UpdatingImageTag:
    needs: [dockerBuildAndPush]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Updating Image tag to deploy
        run: |
            ls
            pwd
            ls 
            sed -i -e "s/minamaherdocker\/blogsapp:.*/minamaherdocker\/blogsapp:${{github.sha}}/g" gitops/blogsApp.yaml
            cat gitops/blogsApp.yaml
            git config --global user.name 'MIna-Maher'
            git config --global user.email 'm.maher.eng2014@gmail.com'
            git commit -am "Updating Image to ${{github.sha}}"
            git push